Iframe testing orb scheme (#85)
* IFrame player page

* orb:// scheme example

* Update MockTvBrowserCallback setDvbVideoRectangle implementation to match new API. (#72)

* Implementation of MediaElementWrapper that will serve as a proxy to the iframe's media element and the base html page.

* Use window.sendMessage() to request properties or call functions within the iframe in order to bypass CORS.

* Update main window properties when a change occurs in one of the iframe properties.

* Refactored communication related code between main window and the iframe, in order to improve management in object level.

* Introduced IFrameObjectProxy as a manager responsible for syncing iframe objects with the main window objects.

* Implemented asynchronous calls with IFrameObjectProxy.
Removed redundant code in mediamanager.js.

* Made IFrameObjectProxy return a promise when initiating handshake, so that we can add a callback when the handshake is complete.

* Mirror attributes to properties in MediaElementWrapper.
Some bug fixing in the process.

* Fixed issue with audio and video tracks proxy due to faulty if statement when requesting properties.
Added helpful comments in the IFrameObjectProxy.

* Create a single IFrameObjectProxy for each iframe and register objects to be updated.

* Major refactoring of iframe related objects.

* Implemetation of TextTrackList with IFrameObjectProxy.

* Toggle unselect current track when another track gets selected.

* Fix for undefined subtitle language.

* Removed redundant code.

* Make text track renderingType property modifiable.

* Removed redundant code from iframe related modules.

* Run jsbeautify.

* Encapsulate iframe logic with function closure.

* due to a runtime i/o error browser could not load our iframe polyfill
1. iframe i/o error (moved the cat operation first in buildPolyfill.mk)
2. playerpage i/o error (forced asset manager to list the files in polyfill dir before appending operation in htmlBuilder.java)

* - dont change playstate when an empty source is loaded
- iframe renamed videowrapper to videoelement
- dont upgrade when source is empty

* Implemented missing methods insertBefore and removeChild in MediaElementWrapper.

* Moved MediaElementWrapper code from objectmanager.js to mediaelementwrapper.js.
Overrided Node.appendChild and Node.insertBefore in order to return the upgraded MediaElementWrapper objects with getElementsByTagName.

* Apply external css meant for video elements to MediaElementWrapper.

* Improve css adaptation from HTMLVideoElement to MediaElementWrapper.

* Override id property for MediaElementWrapper in order to do proper styling when changed.

* Do not set all css properties to initial values on MediaElementWrapper as this will cause the hidden property to be ignored when set.

* Populate audio and video tracks for native playback as they appear in their respective own property descriptor.

* Fixed undefined reference to object.

* Keep the original video element in the DOM tree and copy its style to the iframe whenever there is a change to it.

* Fixed typo.

* Set the ready state to HAVE_NOTHING when a new src is applied to the media element.
Update iframe CSS when hidden property is changed.
Update the iframe src even when the new value is the same as the current value.

* Alternate between audio and video tags within the AVControl object depending on the mimetype.

* Insert the iframe right after the media element if there are other siblings on the parent node.

* Upgrade the video element created within the AV control within it.

* Upgrade video element in at a more apropriate time.

* wip patches

* Fix faulty positioning of the A/V Control media element.

* Move the A/V control addition and removal from DOM tree logic from objectmanager.js to avcontrol.js.

* Additional fix for iframe positioning.

* Prevent call to nofication of A/V control is not is use if there is another object that is currently playing.

* Call unloadSource only when video queue is empty.

* Fix for handling 404 errors when the manifest containg UTC timing elements in DASH playback.
Acquire the ip address before the error as sometimes the request is completed after the player is closed.
Fix for the case the data property of the A/V control is set by modifying the innerHTML property of its parent.

* Upgrade media element as soon as it gets created with document.createElement().

* keep a URL reference in case a test/portal overrides the native javascript object
add a setting in order to change the dash.js debug level

* Convert relative paths to absolute before providing them to the iframe src.

* Update the error property of the media element on both ends.

* Extract the href from the newly set src using new URL, only when it is defined.

* Fix for relative paths with the iframe.

* Remove src attribute before calling load(), as we end up making double requests to the report server in case of DASH playback.

* Fix for non-dispatching cuechange event with the iframe.

* replace magic suffix with orb player url
always use <base> html element when intercepting the orb request

Co-authored-by: josh <joshua.house@oceanbluesoftware.co.uk>
Co-authored-by: Marios Christoforakis <marios.christoforakis@oceanbluesoftware.co.uk>
Co-authored-by: Conor <conor.mcguigan@oceanbluesoftware.co.uk>